name: Shell Lint

on:
  push:
    paths:
      - 'scripts/*.sh'
  pull_request:
    paths:
      - 'scripts/*.sh'

jobs:
  shellcheck:
    name: ShellCheck Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@v2
        with:
          severity: warning
